# Generated by Django 6.0.3 on 2026-03-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('emoji', models.CharField(default='🏙', max_length=10, verbose_name='Эмодзи')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('stars', models.IntegerField(default=5, verbose_name='Звёзды')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Фото')),
                ('amenities', models.CharField(blank=True, max_length=500, verbose_name='Удобства (через запятую)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['-created_at'],
            },
        ),
    ]
