# Generated by Django 6.0.3 on 2026-03-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_guests',
            field=models.IntegerField(default=2, verbose_name='Макс. гостей'),
        ),
    ]
