# Generated by Django 6.0.3 on 2026-03-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotel_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='emoji',
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото города'),
        ),
    ]
