# Generated by Django 6.0.3 on 2026-03-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_city_emoji_city_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('departure', models.DateTimeField(verbose_name='Дата вылета')),
                ('arrival', models.DateTimeField(verbose_name='Дата прилёта')),
                ('airline', models.CharField(max_length=100, verbose_name='Авиакомпания')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='core.city', verbose_name='Откуда')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='core.city', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
    ]
