# Generated by Django 6.0.3 on 2026-03-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
