# Generated by Django 6.0.3 on 2026-03-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotel_latitude_hotel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
    ]
