# Generated by Django 6.0.3 on 2026-03-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
