# Generated by Django 6.0.3 on 2026-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='baggage',
            field=models.CharField(default='Багаж 23 кг — 1 шт', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='hand_luggage',
            field=models.CharField(default='Ручная кладь 10 кг — 1 шт', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='transfers',
            field=models.IntegerField(default=0),
        ),
    ]
